In [2]:
from pathlib import Path

dir_evals = Path('docs/temp/evals')
if not dir_evals.exists(): print(f"Directory {dir_evals} does not exist.")

tools = ['chatgpt_deepresearch', 'manus_ai', 'discourse2draft']

In [3]:
import re
from src.backend.ai.llms import getAIModel
from pydantic import BaseModel, Field
from langchain.output_parsers.fix import OutputFixingParser
from langchain_core.output_parsers import PydanticOutputParser
from src.backend.ai.prompts import setPrompt
from src.backend.utils import Config
import pandas as pd

class StandardizeSectionHeadersSchema(BaseModel):
    '''
    Returns the mapping from the section header to standard section header
    '''
    mapping: dict[str, str] = Field(description='A mapping from the section header to standard section header')

def standardizeHeader(section_headers, section_headers_standard):

    llm = getAIModel(model_name='azure-gpt-4o')
    system_prompt = 'You are an AI assist designed to standardize section headers in a document'
    human_prompt = '''
                You will be provided with a document which is a list of section headers.
                You will also be provided with a list of standard section headers.
                Your task is to map each provided section header to a standard section header.
                If there is no mapping possible, map the section header to itself.

                <Section headers>
                {section_headers}
                </Section headers>

                <Standard section headers>
                {section_headers_standard}
                </Standard section headers>
                '''
    
    parser = OutputFixingParser.from_llm(parser=PydanticOutputParser(pydantic_object=StandardizeSectionHeadersSchema), 
                                llm=llm,
                                max_retries=Config.RETRY_COUNTER)
    
    prompt = setPrompt(system_prompt, human_prompt, parser)
        
    response = (prompt | llm | parser).invoke(input={'section_headers': section_headers, 'section_headers_standard': section_headers_standard})
    return dict(response)['mapping']

def extractSectionContent(file_path):
    
    with open(file_path) as fp:
        data = '\n'.join([line.strip() for line in fp.readlines()])
    
    output = re.findall(r'(#+ .+\n?)([^#]+)', data)
    return [(section.strip(), content.strip()) for section, content in output]

def getSectionAndContent(file_path, section_headers_standard):
    doc = extractSectionContent(file_path)
    doc_san = []
    for section, content in doc:
        if section.startswith('# '):
            doc_san.append(['# Title', section[2:]])
        elif section.startswith('## '):
            doc_san.append([section, content])
        else:
            doc_san[-1][1] += section + '\n' + content
    section_headers = [section for section, _ in doc_san]
    mapping = standardizeHeader(section_headers, section_headers_standard)
    return [(mapping.get(section, section), content) for section, content in doc_san]
        
def getSectionsForComparison(file_name):

    section_headers_standard = [item for item in extractSectionContent(dir_evals / 'prompts' / file_name) if not item[0].startswith('# ')]
    responses = {tool: dict(getSectionAndContent(dir_evals / tool / file_name, section_headers_standard)) for tool in tools}
    
    return pd.DataFrame(responses)

In [ ]:
from langchain_core.output_parsers import PydanticOutputParser
from langchain.output_parsers.fix import OutputFixingParser
from pydantic import BaseModel, Field
from src.backend.ai.prompts import setPrompt
from src.backend.ai.common import StateContentManager
from src.backend.utils import Config

class ScoreWithReasonSchema(BaseModel):
    '''
    Returns a score within 0 to 100 for a particular criterion and a statement supporting the score
    '''
    score: int = Field(description='Score within 0 to 100')
    reason: str = Field(description='A short statement supporting the score')

class RateContentSchema(BaseModel):
    '''
    Returns scores based on different criteria to rate the content of a structured document
    '''

    relevance: ScoreWithReasonSchema = Field(description='A score with supporting statement that evaluates the Relevance of the content')
    continuity: ScoreWithReasonSchema = Field(description='A score with supporting statement that evaluates the Continuity of the content')
    non_repetitiveness: ScoreWithReasonSchema = Field(description='A score with supporting statement that evaluates the Uniqueness (or non-repetitiveness) of the content')
    specificity: ScoreWithReasonSchema = Field(description='A score with supporting statement that evaluates the Specificity of the content')
    #relevance of citation (hallucination), accuracy of the content+citation (hallucination), specificity of the content

# ---------------------------------------------------------------------------
class RateContent:

    rate_content_system_prompt = '''\
    You will be provided a manuscript section header with or without previously written content summary on a specific topic. You are a scholarly reviewer with expertise in the corresponding topic area. Your task is review and rate the section content.
    
    <Instructions>
    - Rating must be an integer number within 0 (lowest) and 100 (highest).
    - Rating will base on the following criteria.
    **Relevance:** Is the content relevant to the provided section header and the summary (if provided).
    **Continuity:** Is the content writing style is continuous with the previously written content summary. Put the highest score if previously written content summary is not provided.
    **Non-Repetitiveness:** Is the content devoid of repetitiveness compared with the previously written content summary. Put the highest score if previously written content summary is not provided.
    **Specificity:** Is the content devoid of halucination.
    </Instructions>
    '''

    rate_content_human_prompt = '''
    <Previous Content Summary>
    {content_pre}
    </Previous Content Summary>

    <Current Section Header>
    {current_section}
    </Current Section Header>

    <Content>
    {content}
    </Content>
    
    <Instructions>
    - Read the Previous Content Summary. 
    - Review the provided content based on the Current Section Header
    - Provide the output in the following format.
    {format_instructions}
    
    - Output must be in JSON format with `json` tags.
    </Instructions>
    '''

    def __init__(self, llm):

        parser = OutputFixingParser.from_llm(parser=PydanticOutputParser(pydantic_object=RateContentSchema), 
                                             llm=llm,
                                             max_retries=Config.RETRY_COUNTER)
        
        self.rate_content_prompt = setPrompt(self.rate_content_system_prompt, self.rate_content_human_prompt, parser)
        
        self.rate_content_chain = self.rate_content_prompt | llm | parser


    def __call__(self, state: StateContentManager):
        '''LLM generates reports from a given outline'''
        
        response = self.rate_content_chain.invoke(input={'content_pre': state['content_pre'],
                                                             'current_section': state['current_section'],
                                                             'content': state['content']})
        try:
            content = dict(response)
        except:
            raise Exception(f'GenerateContent response does not have content, response: {response}')

        return {'content': content, 'steps': ['Rate Content']}
    
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import START, END, StateGraph
from src.backend.ai.llms import getAIModel
from src.backend.ai.summarize import Summarize
from typing import Literal

# -----------------------------------------------------------------------
def check_if_summary_needed(
        state: StateContentManager,
    ) -> Literal['Summarize', 'Rate Content']:
        if len(state.get('content_pre').split()) > 500:
            return 'Summarize'
        return 'Rate Content'

# -----------------------------------------------------------------------
class ContentWriterArchitecture:
     
     def __init__(self, model_name, temperature):
        llm = getAIModel(model_name=model_name, temperature=temperature)

        # Define a new graph
        workflow = StateGraph(state_schema=StateContentManager)

        # Define the (single) node in the graph
        workflow.add_node("Summarize", Summarize(llm=llm, input_field='content_pre'))
        workflow.add_node("Rate Content", RateContent(llm=llm))
        #workflow.add_node("Add Citations", AddCitations(llm))

        workflow.add_conditional_edges(START, check_if_summary_needed)
        workflow.add_edge("Summarize", "Rate Content")

        self.agent = workflow.compile()

In [6]:
file_names = ['CRISPR-based editing for inherited blood disorders.md', 'Phthalates Toxicity.md', 'PFAS.md']

for file_name in file_names:
    print(f'Processing "{file_name}"...')
    display(getSectionsForComparison(file_name))

Processing "CRISPR-based editing for inherited blood disorders.md"...

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:18:50 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:18:50 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:18:52 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:18:54 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:07 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:07 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:12 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:13 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:13 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:13 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:15 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:17 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

,chatgpt_deepresearch,manus_ai,discourse2draft
# Title,State-of-the-Art Scientific Report on CRISPR/C...,"""J. Okalova. Next generation targeted non-geno...",CRISPR-based editing for inherited blood disor...
## Executive Summary,The therapeutic landscape for inherited hemogl...,"Inherited hemoglobinopathies, notably Sickle C...",CRISPR genome editing offers new treatments fo...
## Molecular Mechanisms of Action,### CRISPR–Cas9 in Hematology: Targeting the B...,The current generation of gene editing therapi...,CRISPR-Cas9 has emerged as a versatile genome-...
## Clinical Landscape: Hemoglobinopathies,### Sickle Cell Disease (SCD)\nSCD is an autos...,The clinical efficacy of $\text{CRISPR-Cas9}$ ...,Sickle cell disease (SCD) and β-thalassemia re...
"## The ""Ex Vivo"" Protocol & Technical Challenges",### Autologous HSCT Gene-Editing Workflow\nCur...,The current clinical protocol for Casgevy is a...,In the standard ex vivo protocol for CRISPR-ba...
## Future Horizons: In Vivo Delivery,### Barriers to In Vivo HSC Editing\nIn vivo d...,The logistical complexity and toxicity of the ...,In vivo CRISPR-mediated treatments for inherit...
## Commercial & Ethical Analysis,### Cost Analysis and Current Pricing Models\n...,The commercialization of gene editing therapie...,Commercial deployment of CRISPR-based therapie...
## Key Terminology,**Adenine Base Editor (ABE):** An engineered e...,| Term | Definition ...,NaN
## References,"Agarwal, R., et al. (2025). Busulfan-free stem...",[1]:,"[1]: Bernaudin, F. (2019). Why, Who, When, and..."

Processing "Phthalates Toxicity.md"...

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:17 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:17 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:19 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:21 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:21 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:21 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:24 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:26 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:26 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:26 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:28 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:30 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

,chatgpt_deepresearch,manus_ai,discourse2draft
# Title,"Phthalate Toxicity: Mechanistic, Toxicokinetic...","""Tickner, J. A., Schettler, T., Guidotti, T., ...",Phthalates Toxicity
## **1. Executive Summary**,**Ortho-phthalates** are a class of dialkyl or...,**Ortho-phthalates** are a class of synthetic ...,Phthalates are widely used plasticizers found ...
## **2. Classification and Exposure Assessment**,Phthalates are commonly classified by molecula...,Phthalates are structurally categorized based ...,Phthalate esters are typically classified into...
## **3. Toxicokinetics (ADME)**,"Following exposure, phthalates are absorbed ef...",The toxicokinetics of phthalates are character...,Phthalates display varying degrees of absorpti...
## **4. Molecular Mechanisms of Action**,The toxicological profile of ortho-phthalates ...,Phthalates exert their toxicity through multip...,Phthalates exert their toxicity through multip...
## **5. Organ-Specific Toxicity (Evidence Review)**,The strongest and most consistent evidence con...,Epidemiological evidence strongly supports the...,Phthalates exert organ‑specific toxic effects ...
## **6. Vulnerable Populations**,Particular concern centers on exposure during ...,The **first 1000 days** (from conception to tw...,"The first 1,000 days, encompassing gestation t..."
## **7. Regulatory Landscape & Tolerable Limits**,Regulatory agencies have established health-ba...,Regulatory bodies worldwide employ different m...,Regulatory policies for phthalates typically r...
## **8. Emerging Science & Alternatives**,"In response to regulatory pressure, industry h...",The phase-out of certain phthalates has led to...,In response to regulatory restrictions on trad...
## **9. Conclusion & Future Directions**,Phthalates represent one of the most thoroughl...,Phthalate toxicity is a complex and well-docum...,Phthalates will likely continue to pose signif...
## References,NaN,[1]: https://pmc.ncbi.nlm.nih.gov/articles/PMC...,"[1]: Giuliani, A., Zuccarini, M., Cichelli, A...."

Processing "PFAS.md"...

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:30 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:30 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:33 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:34 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:34 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:34 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:36 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:37 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:24:37 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:24:37 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:24:39 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:24:41 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

,chatgpt_deepresearch,manus_ai,discourse2draft
# Title,Health Impacts of Per- and Polyfluoroalkyl Sub...,Health Impacts of Per- and Polyfluoroalkyl Sub...,PFAS
## Abstract:,Per- and polyfluoroalkyl substances (PFASs) ar...,Per- and polyfluoroalkyl substances (PFASs) re...,Per- and polyfluoroalkyl substances (PFAS) are...
## Introduction & Chemical Background:,Per- and polyfluoroalkyl substances (PFASs) re...,Per- and polyfluoroalkyl substances (PFASs) ar...,Per- and polyfluoroalkyl substances (PFAS) are...
## Exposure Pathways & Toxicokinetics:,**Exposure Pathways:** Human exposure to PFASs...,### 2.1. Exposure Pathways\nHuman exposure to ...,Drinking water contamination has emerged as a ...
## System-Specific Health Impacts (The Core Analysis):,### Immunotoxicity\nOne of the most sensitive ...,The evaluation of health impacts is based on t...,Immunotoxicity. There is sufficient evidence t...
## Mechanisms of Action:,Elucidating how PFASs cause the array of obser...,The biological plausibility of the observed he...,PFAS interactions with peroxisome proliferator...
"## The ""GenX"" Problem:","By the early 2000s, scientific and regulatory ...",The phase-out of PFOA and PFOS led to the intr...,In response to regulatory pressure and steward...
## Regulatory Context & Knowledge Gaps:,**Regulatory Context:** Confronted with mounti...,### 6.1. Regulatory Context\nRegulatory bodies...,"In March 2023, the U.S. Environmental Protecti..."
## Conclusion:,PFASs have transitioned from scientific obscur...,The weight of evidence from both epidemiologic...,"Despite phasedown of legacy long-chain PFAS, t..."
## References,1. **American Bar Association (ABA)**. (2022)....,[1]: https://pmc.ncbi.nlm.nih.gov/articles/PMC...,"[1]: Mazumder, N., Hossain, M. T., Jahura, F. ..."

In [8]:
agent = ContentWriterArchitecture(model_name='azure-o3', temperature=0).agent

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:26:38 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:26:38 [INFO] Calling src.backend.ai.prompts.setPrompt

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:26:38 [INFO] Calling src.backend.ai.prompts.setPrompt

In [ ]:
import tqdm
import pandas as pd

# relevance, continuity, uniqueness, relevance of citation (hallucination), accuracy of the content+citation (hallucination), specificity of the content

from pathlib import Path

def formatRating(rating, tool):
    rating_dict = {}
    for criterion in rating:
        rating_dict[f'{tool} {criterion} (score)'] = rating[criterion].score
        rating_dict[f'{tool} {criterion} (reason)'] = rating[criterion].reason

    return rating_dict

file_names = ['CRISPR-based editing for inherited blood disorders.md', 'Phthalates Toxicity.md', 'PFAS.md']

for file_name in file_names:
    print(f'Processing "{file_name}"...')
    section_sets = getSectionsForComparison(file_name)
    content_pre_sets = ['' for _ in section_sets]
    rating_responses = {}
    for index, row in tqdm.tqdm(section_sets.iterrows()):
        
        section_header = row.name
        print(section_header)
        
        rating_respons_section_wise = {}
        for i, tool in enumerate(tools):
            
            print(tool)

            content = row[tool] if not pd.isna(row[tool]) else ''

            if content.strip() == '': continue
            
            rating_response = agent.invoke({'current_section': section_header, 'content': content, 'content_pre': content_pre_sets[i]})['content']
            rating_respons_section_wise |= formatRating(rating_response, tool)

            content_pre_sets[i] += f'{section_header}\n\n{content}'

        rating_responses[section_header] = rating_respons_section_wise

    rating_responses = pd.DataFrame(rating_responses)

    rating_score = rating_responses.loc[rating_responses.index.str.endswith('(score)')]
    rating_reason = rating_responses.loc[rating_responses.index.str.endswith('(reason)')]

    rating_score = rating_score.rename(index=lambda x:x.replace(' (score)', ''))
    rating_reason = rating_reason.rename(index=lambda x:x.replace(' (reason)', ''))

    rating_score.to_csv(dir_evals / 'scores' / f'{Path(file_name).stem}.csv', index=True)
    rating_reason.to_csv(dir_evals / 'reasons' / f'{Path(file_name).stem}.csv', index=True)

Processing "CRISPR-based editing for inherited blood disorders.md"...

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:58:20 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:58:20 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:58:22 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:58:23 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:58:23 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:58:23 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:58:27 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"
2026-01-22 09:58:28 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

Calling src.backend.ai.llms.getAIModel

2026-01-22 09:58:28 [INFO] Calling src.backend.ai.llms.getAIModel

Calling src.backend.ai.prompts.setPrompt

2026-01-22 09:58:28 [INFO] Calling src.backend.ai.prompts.setPrompt
2026-01-22 09:58:30 [INFO] HTTP Request: POST https://litellm.toxpipe.niehs.nih.gov/chat/completions "HTTP/1.1 200 OK"

In [17]:
rating_score.rename(index=lambda x:x.replace(' (score)', ''))

,# Title,## **1. Executive Summary**,## **2. Classification and Exposure Assessment**,## **3. Toxicokinetics (ADME)**,## **4. Molecular Mechanisms of Action**,## **5. Organ-Specific Toxicity (Evidence Review)**,## **6. Vulnerable Populations**,## **7. Regulatory Landscape & Tolerable Limits**,## **8. Emerging Science & Alternatives**,## **9. Conclusion & Future Directions**,## References
chatgpt_deepresearch relevance,90,95,90,90,90,90,85,90,80,82,NaN
chatgpt_deepresearch continuity,100,98,85,88,85,95,80,85,85,75,NaN
chatgpt_deepresearch non_repetitiveness,100,98,95,95,80,92,85,90,90,92,NaN
chatgpt_deepresearch specificity,85,90,88,85,88,88,90,75,75,80,NaN
manus_ai relevance,20,60,95,90,90,90,90,93,90,92,90
manus_ai continuity,100,80,90,85,88,85,85,90,85,88,85
manus_ai non_repetitiveness,100,90,85,80,92,80,80,96,95,90,95
manus_ai specificity,70,78,90,88,85,85,85,88,82,85,80
discourse2draft relevance,40,95,92,92,92,80,90,90,90,92,85
discourse2draft continuity,90,95,85,88,88,85,85,85,85,87,90
discourse2draft non_repetitiveness,95,95,90,87,85,70,88,92,75,78,95
discourse2draft specificity,20,90,88,82,80,80,80,70,80,85,70

In [43]:
rating_responses = pd.DataFrame(rating_responses)

rating_responses.loc[rating_responses.index.str.endswith('(reason)')]

,# Title,## Executive Summary
chatgpt_deepresearch relevance (reason),"The section header is '# Title', and the provi...","Concise overview touches on clinical context, ..."
chatgpt_deepresearch continuity (reason),"No previous content summary exists, so continu...","Flows naturally from the report title, providi..."
chatgpt_deepresearch non_repetitiveness (reason),"The content consists of a single, non-repetiti...",No redundancy detected within this section and...
chatgpt_deepresearch specificity (reason),The title precisely identifies CRISPR/Cas9 and...,"Includes concrete details (exa-cel mechanism, ..."
manus_ai relevance (reason),The section header indicates this should be th...,"Discusses HSC gene-editing therapy, which is t..."
manus_ai continuity (reason),"No previous content summary exists, so continu...","With only the manuscript title available, styl..."
manus_ai non_repetitiveness (reason),"With no earlier content to repeat, the provide...",No internal repetition and no earlier content ...
manus_ai specificity (reason),"Content is concise and factual; however, inclu...","Provides accurate, concrete details (e.g., Exa..."
discourse2draft relevance (reason),The content is clearly a title and matches the...,Concise overview directly addresses CRISPR-bas...
discourse2draft continuity (reason),"No previous content was provided, so continuit...",No prior executive-summary text to match; tone...
discourse2draft non_repetitiveness (reason),With only one short phrase present and no prio...,Within the brief passage there is minimal inte...
discourse2draft specificity (reason),The title is specific and accurate to the topi...,"Provides accurate examples (e.g., sickle cell,..."

[('# CRISPR-based therapeutic genome editing for inherited blood disorders\n## Therapeutic challenges\n### Chemotherapy-free cell therapies',
  ['\nAutologous gene therapies, including exa-cel, typically rely on myeloablative conditioning to facilitate the engraftment of engineered HSPCs12,168,173. Although non-myeloablative chemotherapy can be sufficient for gene-corrected cells with a selective advantage to reach therapeutic levels, myeloablation is necessary for therapeutic indications dependent on high levels of engraftment, such as β-haemoglobinopathies and lysosomal storage disorders217. HSC gene therapies are therefore limited to the most severe forms of blood disorders, because genotoxic conditioning prior to transplantation is associated with acute toxicities such as cytopenias, mucositis, infection and organ injury (requiring inpatient support for 1–2\u2009months), as well as long-term toxicities such as infertility, organ toxicity and risk of secondary malignancy134,166. In addition, stem cell collection can be onerous. Beam Therapeutics acknowledged the death of a patient due to respiratory failure 4\u2009months after BEAM-101 infusion during a phase I/II clinical trial of base editing for SCD (NCT05456880)218 (Table 1). The complications were likely related to the myeloablative conditioning step using the DNA alkylating agent busulfan218. Also, the death of a patient with SCD was reported in the exa-cel trial, attributed to respiratory failure associated with coronavirus 2 (SARS-CoV-2) infection, along with busulfan-associated lung injury and pre-existing lung disease147.\n\nNon-genotoxic conditioning regimens could improve the safety profile of autologous HSC-based therapies. Antibody–drug conjugates (ADCs) targeting antigens such as CD117/c-kit and CD45 expressed on HSCs might produce myeloablation and enable haematopoietic repopulation219,220,221,222. Studies in non-human primates have indeed shown that such ADCs allow for durable haematopoietic replacement by gene-modified HSCs223,224. A challenge is that no single antigen is expressed solely on HSCs — for example, CD117 is also expressed on mast cells, germ cells and various other non-haematopoietic cells, and CD45 on mature haematopoietic cells. A clinical trial testing an anti-CD117 ADC was paused following the death of a patient from cardiorespiratory failure225, suggesting that the clinical implementation of ADC-based myeloablative conditioning will require careful determination of safe and effective treatment regimens.\n\nA promising alternative to toxic conditioning could be to mobilize existing HSPCs out of their niche while conferring a selective advantage to engineered cells, enabling efficient competitive engraftment. This paradigm has been exemplified by co-delivering mRNA to overexpress the homing receptor CXCR4 to repopulate bone marrow after prior mobilization treatment to produce niche space availability226. In addition, conferring selective advantage by multiplexed genome editing might help achieve therapeutic levels of editing without myeloablative conditioning. Targeting two endogenous loci with CRISPR–Cas9 results in double-editing events that are not statistically independent across a wide range of biological systems, including in Caenorhabditis elegans227, Drosophilia melanogaster228,229, and human cells108,230. Genome editing at a selectable endogenous gene enables the enrichment of a second genome modification of interest via marker-free co-selection, a process compatible with NHEJ, HDR, base editing and prime editing108,230. The mechanism of co-selection is not fully understood, but likely involves a combination of factors. Co-editing events might occur in cells that have the highest editor expression while being in a similar cell cycle stage and expressing the most favourable DNA repair factors. Additionally, other metabolic features might make some cells more amenable to completing multiple editing events at different loci. Building on this, strategies can be envisioned to improve the enrichment and engraftment of gene-corrected HSCs through CRISPR-driven introduction of selectable alleles. For example, epitope base editing of surface receptors in HSPCs confers resistance to monoclonal antibodies and chimeric antigen receptor (CAR) T cells, while maintaining receptor expression and function, and has enabled targeted immunotherapies for acute myeloid leukaemia, B cell lymphoma and T cell leukaemia231,232. Multiplexed epitope and therapeutic editing is a promising approach to engineer resistance to clinically used antibodies, which could be leveraged to enrich HSCs that harbour a therapeutic edit at a second locus of interest. Considering the progress made towards delivery of genome editors to HSCs in vivo233,234, marker-free co-selection strategies could facilitate gene therapy for severe blood disorders without ex vivo engineering and myeloablative conditioning.\n\n',
   'The bone marrow failure syndromes encompass a heterogeneous group of rare, monogenic disorders that lead to reduced hematopoietic output due to defects in diverse cellular processes such as DNA damage response, telomere maintenance, ribosome biogenesis, or proteostasis. For example, dyskeratosis congenita (DC) is linked to impaired telomere function (CS=10) while Diamond‐Blackfan anemia (DBA) is associated with defects in ribosomal proteins, leading to ineffective erythropoiesis (CS=9). Zebrafish models have provided evidence that activation of the TP53 pathway plays a central role in mediating marrow failure in these syndromes, suggesting that a stress response is triggered by defective DNA repair and other forms of cellular perturbation (CS=9) [14].\n\nIn patients with β‐haemoglobinopathies, the molecular pathology is equally complex. Sickle cell disease, for instance, is caused by a single base substitution in the β‐globin gene that leads to the replacement of glutamic acid with valine, triggering polymerization of sickle hemoglobin and resultant vaso-occlusion (CS=10). In contrast, β‐thalassemia typically involves mutations that cause reduced or absent production of beta-globin chains, with consequent accumulation of unpaired alpha-globin precipitates in erythroid precursors (CS=10). Together, these disorders contribute significantly to global morbidity, particularly in populations from the Mediterranean, Asia, and Africa (CS=10) [1].\n\nCRISPR-based genome editing strategies for hematopoietic stem cells (HSCs) are emerging as powerful tools to correct such inherited blood disorders. The efficiency of these approaches relies on the delicate balance between error-prone non-homologous end joining (NHEJ) and high-fidelity homology-directed repair (HDR) pathways (CS=9). While HDR has enabled precise correction by templated repair, its restricted activity during the S/G2 cell cycle phases limits its use in quiescent HSCs (CS=9). In order to overcome these limitations, alternative techniques such as base editing and prime editing have been developed; the former allows single nucleotide modifications without double-strand break (DSB) formation, and the latter further enables targeted insertions or deletions while avoiding DSBs (CS=9). However, both editing strategies require highly efficient and specific delivery to HSCs, given their quiescent state and complex niche environment (CS=8) [11].\n\nEx vivo manipulation of HSCs, combined with innovative delivery platforms, has significantly enhanced engraftment and therapeutic outcomes. Advances in non-viral delivery systems – particularly those utilizing stimuli-responsive nanoformulations – have improved the intracellular uptake of CRISPR components and minimized immune responses (CS=8). Moreover, targeted integration strategies that use safe harbor loci further mitigate the risks associated with random integration, thereby enhancing the precision and safety of gene correction in autologous HSC therapy (CS=9) [8, 11].\n\nIt is also critical to consider that the quiescent state of HSCs, maintained by a unique metabolic and transcriptional profile in a hypoxic bone marrow niche, poses additional challenges for efficient genome editing. Quiescence minimizes replication-induced errors but also restricts access to HDR-mediated repair pathways (CS=9). Recent advances in our understanding of stem cell quiescence have highlighted the role of key regulators—including HIF-1α and Meis1—in balancing glycolytic flux and mitochondrial respiration, thereby preserving the long-term regenerative potential of HSCs (CS=9) [17, 22].\n\nFinally, long-term safety remains a paramount consideration in clinical translation. Off-target effects of CRISPR-Cas9, even though now mitigated through the development of high-fidelity nucleases and improved guide RNA designs, still require rigorous evaluation through deep sequencing and unbiased genome-wide assays (CS=9). In addition, immune responses against CRISPR components and delivery vehicles can compromise cell viability and function, emphasizing the importance of controlled, transient expression systems (CS=8) [1, 15].\n\nCollectively, these developments underscore both the potential and the challenges of applying CRISPR-based genome editing to treat inherited blood disorders. The integration of precise editing technologies with optimized ex vivo expansion and non-cytotoxic conditioning regimens heralds a new era in HSC gene therapy, promising durable and potentially curative treatments with minimal adverse effects (CS=9) [2, 5].\n']),
 ('# CRISPR-based therapeutic genome editing for inherited blood disorders\n## Improving broad patient access',
  ['\nThe current model for the development of gene and cell therapies poses translational challenges for their broad accessibility to patients with severe blood disorders. This is especially true for rare genetic diseases that are not viable for pharmaceutical commercialization. For common blood disorders with a universal therapeutic strategy, such as the restoration of HbF expression for β-haemoglobinopathies, the main contemporary barriers are patient acceptance of therapies that, although potentially transformational, are still associated with substantial toxicity and complexity, the healthcare infrastructure needed to administer the autologous cell therapy, and the scientific and medical expertise needed to produce and administer gene therapies (Fig. 4). HSC mobilization, isolation and ex vivo manufacturing require extensive resources and scientific expertise. Additionally, administering the conditioning chemotherapy, transfusing engineered cells and monitoring the patient post transplantation necessitate at least 4–6\u2009weeks of hospitalization (Fig. 4). Although potentially curative, the infrastructure and expertise needed to successfully provide the first CRISPR-based gene and cell therapies, as well as their cost235,236, will restrict their widespread administration. Navigating the complex intellectual properties involved in therapeutic genome editing also generates an additional layer of complexity. Considering that more than 300,000 babies are born every year with β-haemoglobinopathies, developing safe and efficient delivery methods to engineer HSCs in vivo could drastically improve broad patient accessibility.\n\n',
   'Improving broad patient access to CRISPR‐based therapies for inherited blood disorders is increasingly recognized as a critical component in translating these transformative technologies into clinically impactful treatments (CS = 10). Recent advancements in CRISPR‐Cas systems—including the development of high‐fidelity nucleases and refined base and prime editing platforms—have been paralleled by innovations in delivery strategies such as stimulus‐responsive, non‐viral nanoparticle formulations. These delivery systems not only enhance the precision and efficacy of gene editing by ensuring selective tissue targeting and efficient cellular uptake but also minimize the risks of immunogenicity and off‐target effects (CS = 9) [1].\n\nFurthermore, contemporary research emphasizes the integration of cost‐effective, robust manufacturing processes with decentralized cell processing to reduce complexities inherent in traditional conditioning regimens and ex vivo expansion of hematopoietic stem cells (HSCs). Innovations such as non‐myeloablative conditioning regimens and novel mobilization approaches have the potential to circumvent the need for high‐dose chemotherapeutic preconditioning, thereby reducing treatment-related morbidity and broadening patient eligibility—particularly among older or medically fragile individuals (CS = 9) [2].\n\nIn addition, strategic improvements in delivery tools, such as the design of nanostructured, stimuli‐responsive carriers, allow for more controlled and transient expression of CRISPR components. This transient delivery mitigates long-term exposure and decreases the risk of undesired genomic alterations while preserving the long-term repopulating potential of gene-edited HSCs. Such developments are vital for ensuring that the benefits of precision genome editing can be distributed equitably, thus making therapies more accessible beyond highly specialized centers (CS = 8) [5].\n\nFinally, the combination of these advances—including improvements in nuclease specificity, optimized donor template designs, and the development of innovative, non-viral delivery systems—paves the way for scalable and cost-effective gene editing platforms. This integrated approach is expected to further reduce overall treatment costs and logistical barriers, thereby facilitating broader clinical adoption and improved patient access to curative treatments for inherited blood disorders (CS = 9) [12].\n']),
 ('# CRISPR-based therapeutic genome editing for inherited blood disorders\n## Improving broad patient access\n### In vivo delivery',

In [46]:
row

chatgpt_deepresearch    **Adenine Base Editor (ABE):** An engineered e...
manus_ai                | Term            | Definition                ...
discourse2draft                                                       NaN
Name: ## Key Terminology, dtype: object

100%|██████████| 30/30 [37:00<00:00, 74.02s/it]